// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kaiachain/kaia/kaiax/vrank/impl (interfaces: ProtocolManager)

// Package impl is a generated GoMock package.
package impl

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	common "github.com/kaiachain/kaia/common"
	consensus "github.com/kaiachain/kaia/consensus"
)

// MockProtocolManager is a mock of ProtocolManager interface.
type MockProtocolManager struct {
	ctrl     *gomock.Controller
	recorder *MockProtocolManagerMockRecorder
}

// MockProtocolManagerMockRecorder is the mock recorder for MockProtocolManager.
type MockProtocolManagerMockRecorder struct {
	mock *MockProtocolManager
}

// NewMockProtocolManager creates a new mock instance.
func NewMockProtocolManager(ctrl *gomock.Controller) *MockProtocolManager {
	mock := &MockProtocolManager{ctrl: ctrl}
	mock.recorder = &MockProtocolManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProtocolManager) EXPECT() *MockProtocolManagerMockRecorder {
	return m.recorder
}

// FindCNPeers mocks base method.
func (m *MockProtocolManager) FindCNPeers(arg0 map[common.Address]bool) map[common.Address]consensus.Peer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCNPeers", arg0)
	ret0, _ := ret[0].(map[common.Address]consensus.Peer)
	return ret0
}

// FindCNPeers indicates an expected call of FindCNPeers.
func (mr *MockProtocolManagerMockRecorder) FindCNPeers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCNPeers", reflect.TypeOf((*MockProtocolManager)(nil).FindCNPeers), arg0)
}
